# Kurt Lyell
# CS370
# Lab3 --makefile
# 01/18/2023
# This makefile will run LEX and compile the program and run it


all: lab3

lab3: symtable.c symtab.h
	gcc symtable.c -o lab3
	
	
run: lab3
	./lab3
clean:
	rm -f lab3

